-- Migration: I have created the 'entries' table in your Supabase database. This table will store all the journal entries and includes columns for an auto-incrementing ID, the description, rating, solution, and a timestamp for when it was created. I've also enabled Row Level Security and set a basic policy that allows all users to read and write data, which is suitable for the current stage of your application.
-- Executed at: 2025-11-02T13:51:42Z
-- Generated by AI Agent


CREATE TABLE entries (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  description TEXT NOT NULL,
  rating REAL NOT NULL,
  solution TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON public.entries FOR ALL USING (true) WITH CHECK (true);

