// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: prejnqvmokxtauofosfv

class SupabaseConfig {
  static const String supabaseUrl = 'https://prejnqvmokxtauofosfv.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZWpucXZtb2t4dGF1b2Zvc2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNDA5MDIsImV4cCI6MjA3NzYxNjkwMn0.p5_DxbrTatwq-FbdUiBx32NfOgNOrDyfbo4GfyZN4k0';
}
